# Generated by Django 3.1.1 on 2020-09-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ShadowAmp',
            field=models.ManyToManyField(blank=True, to='projectApp.ShadowAmp'),
        ),
    ]
